[package]
name = "godot-eqloader"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
libeq = { git = "https://github.com/bryab/libeq", branch = "godot-eqloader" }
image = { version="*", default-features = false, features=["bmp"]}
wav = {version="*"}
owning_ref = "*"